### ISSUE TITLE
使用mdbook-epub编译时无法下载图片

### ISSUE THREAD

**Issue by andyli386** [easychen/one-person-businesses-methodology-v2.0#1]
使用mdbook-epub编译时报错，错误如下

(base) ➜  one-person-businesses-methodology-v2.0 git:(master) mdbook-epub -s true .
Running mdbook-epub as standalone app...
[2024-03-28T06:34:53Z ERROR mdbook_epub] https://res07.ftqq.com/wp-content/uploads/2024/03/image-102.png: status code 403

**Comment by easychen** [comment]
网站图片开启了防盗链，请用预处理脚本对图片做离线处理（header中加上refference）。

**Comment by easychen** [comment]
我写了个脚本本地化了，现在直接编译应该就可以了。

**Comment by 123hurray** [comment]
> 我写了个脚本本地化了，现在直接编译应该就可以了。

还差两张图片：
assets-and-passive-income.md  25行
non-competition-strategy.md 28行

**Comment by easychen** [comment]
修复了，之前漏了jpg格式。

**Comment by factoryfactory** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
hohoc, @punitpratapsingh, @yuraware, @itchii-06, @jaypopat, @agucova, @goranurukalo, @heyong0228, @abdelhai, @Ericcen944, @EndyZhou, @Ewkoll, @cooladam201212, @ahmaduxui, @IMRFeng, @shiruco, @rkirkendall, @cuongtranduc, @EdisonArango, @LeeDongHyeok, @cpxPratik, @MichalCz, @yanisurbis, @web3jt, @hiteshjasani, @sighttviewliu, @werner-duvaud, @mjpowersjr, @lessneek, @isanwenyu, @bitruss, @Zeranamu, @jondashkyle, @alberrrttt, @50574E, @KEVINYZY, @BenSchZA, @dillon, @RawToast, @Lunaticf, @bigbuffetboy420, @ndresx, @Margen67, @loganfreeman, @simonbuechi, @bebetter2018, @huap, @Franceshe, @sengthaite, @RinatValiullovfoonsun, @georgelima, @kalyani2003, @Gannon88, @mattysmith9, @saratsista, @wuyb518, @habibtalib, @simonbuechi, @peizihui, @StarksJohn, @sangbejo, @Taurusu, @billyjov, @abadiu, @africanSuperStar, @onny, @yangblocker, @benjamin-asdf, @timqian, @amite, @libreom, @mr3mre, @westonnelson, @JonathanWilbur, @dengbing88, @serefayar, @Jawn78, @Kirinmaki, @antoninsmetana, @debragail, @ben-29, @dillon, @gustavoabel, @roll, @raspharaoh, @m-yosefpor, @veronicaz41, @sukri557, @peymanslh, @ericren-alation, @jramosg, @usametov, @0frasure, @status-comment-bot, @sikyaNQ, @peterkinalex, @bartekkw, @mjpowersjr, @avocade
